//! Skill self-evolution pipeline: Case -> Cluster -> Skill.
//! Borrowed from EverOS AgentSkillExtractor.
//!
//! Lives in control-plane (not skill-runtime) to avoid circular dependency.
//! Generated SkillDrafts must pass governance approval before SkillHub install.

use cyberclaw_core::case::CaseQuality;
use cyberclaw_core::ids::{ExecutionId, SkillId};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Retirement threshold: confidence < 0.1 triggers removal.
pub const RETIREMENT_CONFIDENCE_THRESHOLD: f32 = 0.1;

/// Dual-track prompt selection threshold (EverOS `FAILURE_QUALITY_THRESHOLD`).
/// Distinct from `SUCCESS_THRESHOLD` (0.6) which gates `is_success_case()`.
/// Scores in [0.5, 0.6) use success prompt but are not full success cases.
pub const DUAL_TRACK_THRESHOLD: f32 = 0.5;

/// Dual-track prompt selection based on case quality.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CaseTrack {
    /// quality >= 0.5: extract reusable steps and patterns.
    Success,
    /// quality < 0.5: extract lessons and improvement directions.
    Failure,
}

impl CaseTrack {
    pub fn from_quality(overall_score: f32) -> Self {
        if overall_score >= DUAL_TRACK_THRESHOLD {
            Self::Success
        } else {
            Self::Failure
        }
    }
}

/// Content change magnitude detection (3-level threshold from EverOS).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ChangeRatio {
    /// < 20% content change.
    Trivial,
    /// 20-40% content change.
    Moderate,
    /// >= 40% content change.
    Major,
}

impl ChangeRatio {
    /// Determine change ratio from a percentage (0.0-1.0).
    pub fn from_percentage(pct: f32) -> Self {
        if pct < 0.2 {
            Self::Trivial
        } else if pct < 0.4 {
            Self::Moderate
        } else {
            Self::Major
        }
    }
}

/// Hypothesis promotion detection result.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HypothesisPromotion {
    pub detected: bool,
    pub promoted_steps: Vec<String>,
}

/// Detect hypothesis promotion by comparing old and new skill content.
pub fn detect_hypothesis_promotion(old_content: &str, new_content: &str) -> HypothesisPromotion {
    let old_has_potential = old_content.contains("## Potential Steps");
    let new_has_confirmed =
        new_content.contains("## Steps") && !new_content.contains("## Potential Steps");

    if old_has_potential && new_has_confirmed {
        let promoted_steps = extract_steps_from_section(new_content, "## Steps");
        HypothesisPromotion {
            detected: true,
            promoted_steps,
        }
    } else {
        HypothesisPromotion {
            detected: false,
            promoted_steps: vec![],
        }
    }
}

/// Extract step titles from a markdown section.
fn extract_steps_from_section(content: &str, section_header: &str) -> Vec<String> {
    let mut in_section = false;
    let mut steps = vec![];

    for line in content.lines() {
        if line.starts_with(section_header) {
            in_section = true;
            continue;
        }
        if in_section && line.starts_with("## ") {
            break; // next section
        }
        if in_section && (line.starts_with("- ") || line.starts_with("* ")) {
            steps.push(
                line.trim_start_matches("- ")
                    .trim_start_matches("* ")
                    .to_string(),
            );
        }
    }

    steps
}

/// Should a skill be retired?
pub fn should_retire(skill_confidence: f32) -> bool {
    skill_confidence < RETIREMENT_CONFIDENCE_THRESHOLD
}

/// A draft skill generated by the evolution pipeline.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillDraft {
    pub name: String,
    pub description: String,
    /// SKILL.md content body.
    pub skill_md_content: String,
    /// Optional scripts (filename -> content).
    pub scripts: HashMap<String, String>,
    /// Source execution IDs that contributed.
    pub source_execution_ids: Vec<ExecutionId>,
    /// Confidence from clustering (0.0-1.0).
    pub confidence: f32,
    pub track: CaseTrack,
}

impl SkillDraft {
    /// Validate script filenames against path traversal and injection.
    pub fn validate_scripts(&self) -> anyhow::Result<()> {
        for filename in self.scripts.keys() {
            if filename.contains("..") || filename.contains('/') || filename.contains('\\') {
                anyhow::bail!(
                    "Script filename '{}' contains path separator or traversal",
                    filename
                );
            }
            if filename.chars().any(|c| c.is_control()) {
                anyhow::bail!("Script filename '{}' contains control characters", filename);
            }
            if filename.len() > 128 {
                anyhow::bail!("Script filename too long: {} chars", filename.len());
            }
        }
        Ok(())
    }
}

/// A patch to update an existing skill.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillPatch {
    pub skill_md_content: Option<String>,
    pub description: Option<String>,
    pub scripts_upsert: HashMap<String, String>,
    pub scripts_remove: Vec<String>,
    pub new_source_execution_ids: Vec<ExecutionId>,
    pub confidence: f32,
    pub hypothesis_promotion: Option<HypothesisPromotion>,
}

/// Incremental operation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SkillEvolutionOp {
    Add(SkillDraft),
    Update {
        skill_id: SkillId,
        patch: SkillPatch,
        change_ratio: ChangeRatio,
    },
    /// No evolution needed (avoids shadowing Option::None).
    NoOp,
}

/// Trait for clustering cases by pattern similarity.
#[async_trait::async_trait]
pub trait CaseClusterer: Send + Sync {
    /// Cluster quality records into groups of similar execution patterns.
    async fn cluster(&self, qualities: &[CaseQuality]) -> anyhow::Result<Vec<Vec<CaseQuality>>>;
}

/// Trait for synthesizing skills from clustered cases.
#[async_trait::async_trait]
pub trait SkillSynthesizer: Send + Sync {
    /// Synthesize a skill evolution operation from a cluster of cases.
    async fn synthesize(
        &self,
        cluster: &[CaseQuality],
        track: CaseTrack,
        existing_skill: Option<(&SkillId, &str)>, // (id, current SKILL.md content)
    ) -> anyhow::Result<SkillEvolutionOp>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_case_track_from_quality() {
        assert_eq!(CaseTrack::from_quality(0.8), CaseTrack::Success);
        assert_eq!(CaseTrack::from_quality(0.6), CaseTrack::Success);
        // 0.5 is the dual-track threshold (EverOS FAILURE_QUALITY_THRESHOLD)
        assert_eq!(CaseTrack::from_quality(0.5), CaseTrack::Success);
        assert_eq!(CaseTrack::from_quality(0.49), CaseTrack::Failure);
        assert_eq!(CaseTrack::from_quality(0.0), CaseTrack::Failure);
    }

    #[test]
    fn test_change_ratio_from_percentage() {
        assert_eq!(ChangeRatio::from_percentage(0.1), ChangeRatio::Trivial);
        assert_eq!(ChangeRatio::from_percentage(0.19), ChangeRatio::Trivial);
        assert_eq!(ChangeRatio::from_percentage(0.2), ChangeRatio::Moderate);
        assert_eq!(ChangeRatio::from_percentage(0.39), ChangeRatio::Moderate);
        assert_eq!(ChangeRatio::from_percentage(0.4), ChangeRatio::Major);
        assert_eq!(ChangeRatio::from_percentage(1.0), ChangeRatio::Major);
    }

    #[test]
    fn test_should_retire() {
        assert!(should_retire(0.05));
        assert!(should_retire(0.09));
        assert!(!should_retire(0.1));
        assert!(!should_retire(0.5));
    }

    #[test]
    fn test_hypothesis_promotion_detected() {
        let old = "## Potential Steps\n- step A\n- step B\n";
        let new_content = "## Steps\n- step A\n- step B\n## Notes\nSome notes";
        let result = detect_hypothesis_promotion(old, new_content);
        assert!(result.detected);
        assert_eq!(result.promoted_steps, vec!["step A", "step B"]);
    }

    #[test]
    fn test_hypothesis_promotion_not_detected() {
        let old = "## Steps\n- step A\n";
        let new_content = "## Steps\n- step A\n- step B\n";
        let result = detect_hypothesis_promotion(old, new_content);
        assert!(!result.detected);
    }

    #[test]
    fn test_hypothesis_promotion_still_potential() {
        let old = "## Potential Steps\n- step A\n";
        let new_content = "## Potential Steps\n- step A\n- step B\n";
        let result = detect_hypothesis_promotion(old, new_content);
        assert!(!result.detected); // Still has "Potential Steps"
    }

    #[test]
    fn test_skill_draft_serde() {
        let draft = SkillDraft {
            name: "auto-review".to_string(),
            description: "Automated code review skill".to_string(),
            skill_md_content: "# Auto Review\nReview code changes.".to_string(),
            scripts: HashMap::new(),
            source_execution_ids: vec![],
            confidence: 0.85,
            track: CaseTrack::Success,
        };
        let json = serde_json::to_string(&draft).expect("serialize");
        let deser: SkillDraft = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(deser.name, "auto-review");
        assert!((deser.confidence - 0.85).abs() < f32::EPSILON);
    }

    #[test]
    fn test_validate_scripts_clean() {
        let draft = SkillDraft {
            name: "test".to_string(),
            description: "test".to_string(),
            skill_md_content: String::new(),
            scripts: HashMap::from([("run.sh".to_string(), "echo hello".to_string())]),
            source_execution_ids: vec![],
            confidence: 0.5,
            track: CaseTrack::Success,
        };
        assert!(draft.validate_scripts().is_ok());
    }

    #[test]
    fn test_validate_scripts_path_traversal() {
        let draft = SkillDraft {
            name: "test".to_string(),
            description: "test".to_string(),
            skill_md_content: String::new(),
            scripts: HashMap::from([("../../etc/cron".to_string(), "bad".to_string())]),
            source_execution_ids: vec![],
            confidence: 0.5,
            track: CaseTrack::Success,
        };
        assert!(draft.validate_scripts().is_err());
    }

    #[test]
    fn test_validate_scripts_slash() {
        let draft = SkillDraft {
            name: "test".to_string(),
            description: "test".to_string(),
            skill_md_content: String::new(),
            scripts: HashMap::from([("dir/file.sh".to_string(), "x".to_string())]),
            source_execution_ids: vec![],
            confidence: 0.5,
            track: CaseTrack::Success,
        };
        assert!(draft.validate_scripts().is_err());
    }

    #[test]
    fn test_skill_evolution_op_noop_serde() {
        let op = SkillEvolutionOp::NoOp;
        let json = serde_json::to_string(&op).expect("serialize");
        let deser: SkillEvolutionOp = serde_json::from_str(&json).expect("deserialize");
        assert!(matches!(deser, SkillEvolutionOp::NoOp));
    }
}
